#!/usr/bin/env python3
"""
Package JUST the Reading 4 (Counting) and Reading 5 (Sets) reading-check quizzes
as a Canvas-native course-export .imscc (quizzes only, no pages, no modules).
Import via: Settings -> Import Course Content -> Canvas Course Export Package.

Reuses the QTI already generated by export.sh in ./out/quizzes, relocates it to
the Canvas-native non_cc_assessments/ layout, gives each quiz a g+md5 identifier,
and adds a 'read this first' link back to the hosted reading.
Run AFTER: bash export.sh <BASE_URL>
"""
import os, re, glob, html, hashlib, zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "out")
BASE_URL = "https://johncbowers.github.io/cs227-readings"
NS_CCC = "http://canvas.instructure.com/xsd/cccv1p0"
XSI = "http://www.w3.org/2001/XMLSchema-instance"
COURSE_TITLE = "CS 227 — Reading Checks (R4–R5)"

# (num, slug, short title, reading filename)
QUIZZES = [
    ("04", "counting", "Counting", "reading-04-counting.html"),
    ("05", "sets", "Sets and Operations", "reading-05-sets.html"),
]

def gid(seed): return "g" + hashlib.md5(seed.encode("utf-8")).hexdigest()
def esc(s): return html.escape(str(s), quote=True)
def cccroot(tag, extra=""):
    return (f'<{tag} xmlns="{NS_CCC}" xmlns:xsi="{XSI}" '
            f'xsi:schemaLocation="{NS_CCC} {NS_CCC}.xsd"{extra}>')

course_id = gid("cs227_r4r5_quizzes_course")
files, resources = {}, []

for num, slug, short, rfile in QUIZZES:
    qdir = os.path.join(OUT, "quizzes", f"reading-{num}-{slug}-check")
    qti = open(glob.glob(os.path.join(qdir, "*", "*_check.xml"))[0], encoding="utf-8").read()
    meta = open(glob.glob(os.path.join(qdir, "*", "assessment_meta.xml"))[0], encoding="utf-8").read()

    quiz_id = gid("quiz_" + num + "_" + slug)
    assign_id = gid("quiz_assign_" + num + "_" + slug)
    meta_res = gid("quiz_metares_" + num + "_" + slug)
    title = f"Reading {num} — {short} — Reading Check"
    disp = f"Reading {num} — {short}"
    link = f"{BASE_URL}/{rfile}"
    desc = (f'<p>First work through the reading: <a href="{link}">{esc(disp)}</a>. '
            f'Then complete this short check.</p>')

    qti = re.sub(r'<assessment ident="[^"]+"', f'<assessment ident="{quiz_id}"', qti, count=1)
    qti = re.sub(r'(<assessment ident="[^"]+") title="[^"]+"', rf'\1 title="{esc(title)}"', qti, count=1)
    meta = re.sub(r'<quiz identifier="[^"]+"', f'<quiz identifier="{quiz_id}"', meta, count=1)
    meta = re.sub(r'<assignment identifier="[^"]+"', f'<assignment identifier="{assign_id}"', meta, count=1)
    meta = re.sub(r"<title>.*?</title>", f"<title>{esc(title)}</title>", meta, count=2)
    meta = re.sub(r"<description>.*?</description>", f"<description>{esc(desc)}</description>", meta, count=1, flags=re.S)

    qti_href = f"non_cc_assessments/{quiz_id}.xml.qti"
    meta_href = f"{quiz_id}/assessment_meta.xml"
    files[qti_href] = qti
    files[meta_href] = meta
    resources.append(
        f'    <resource identifier="{quiz_id}" type="imsqti_xmlv1p2/imscc_xmlv1p1/assessment" href="{qti_href}">\n'
        f'      <file href="{qti_href}"/>\n      <dependency identifierref="{meta_res}"/>\n    </resource>\n'
        f'    <resource identifier="{meta_res}" type="associatedcontent/imscc_xmlv1p1/learning-application-resource" href="{meta_href}">\n'
        f'      <file href="{meta_href}"/>\n    </resource>')

# course_settings stubs
files["course_settings/canvas_export.txt"] = "course, version 1\n"
files["course_settings/course_settings.xml"] = (
    '<?xml version="1.0" encoding="UTF-8"?>\n' + cccroot("course", f' identifier="{course_id}"') + "\n"
    + f"  <title>{esc(COURSE_TITLE)}</title>\n  <course_code>CS227</course_code>\n</course>\n")
for tag, fn in [("modules","module_meta.xml"),("assignmentGroups","assignment_groups.xml"),
                ("fileMeta","files_meta.xml"),("events","events.xml"),
                ("context_info","context.xml"),("media_tracks","media_tracks.xml")]:
    files[f"course_settings/{fn}"] = '<?xml version="1.0" encoding="UTF-8"?>\n' + cccroot(tag) + f"\n</{tag}>\n"
settings_files = ["course_settings/course_settings.xml","course_settings/module_meta.xml",
    "course_settings/assignment_groups.xml","course_settings/files_meta.xml","course_settings/events.xml",
    "course_settings/context.xml","course_settings/media_tracks.xml","course_settings/canvas_export.txt"]

manifest = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    f'<manifest identifier="{course_id}"\n'
    '          xmlns="http://www.imsglobal.org/xsd/imsccv1p1/imscp_v1p1"\n'
    '          xmlns:lom="http://ltsc.ieee.org/xsd/imsccv1p1/LOM/resource"\n'
    '          xmlns:lomimscc="http://ltsc.ieee.org/xsd/imsccv1p1/LOM/manifest"\n'
    '          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
    '          xsi:schemaLocation="http://www.imsglobal.org/xsd/imsccv1p1/imscp_v1p1 '
    'https://www.imsglobal.org/profile/cc/ccv1p1/ccv1p1_imscp_v1p2_v1p0.xsd">\n'
    "  <metadata>\n    <schema>IMS Common Cartridge</schema>\n    <schemaversion>1.1.0</schemaversion>\n"
    "    <lomimscc:lom>\n      <lomimscc:general>\n"
    f"        <lomimscc:title><lomimscc:string>{esc(COURSE_TITLE)}</lomimscc:string></lomimscc:title>\n"
    "      </lomimscc:general>\n      <lomimscc:rights>\n"
    "        <lomimscc:copyrightAndOtherRestrictions><lomimscc:value>yes</lomimscc:value></lomimscc:copyrightAndOtherRestrictions>\n"
    "        <lomimscc:description><lomimscc:string>Private (Copyrighted) - http://en.wikipedia.org/wiki/Copyright</lomimscc:string></lomimscc:description>\n"
    "      </lomimscc:rights>\n    </lomimscc:lom>\n  </metadata>\n"
    "  <organizations>\n"
    '    <organization identifier="org_1" structure="rooted-hierarchy">\n'
    '      <item identifier="LearningModules"></item>\n'
    "    </organization>\n  </organizations>\n"
    "  <resources>\n"
    f'    <resource identifier="{course_id}" type="associatedcontent/imscc_xmlv1p1/learning-application-resource" href="course_settings/canvas_export.txt">\n'
    + "".join(f'      <file href="{f}"/>\n' for f in settings_files) + "    </resource>\n"
    + "\n".join(resources) + "\n  </resources>\n</manifest>\n")

out_path = os.path.join(OUT, "CS227_R4R5_quizzes.imscc")
if os.path.exists(out_path): os.remove(out_path)
with zipfile.ZipFile(out_path, "w", compression=zipfile.ZIP_STORED) as zf:
    zf.writestr("imsmanifest.xml", manifest)
    for arc, data in files.items():
        zf.writestr(arc, data)
print("Wrote", out_path)
